### ISSUE TITLE
Value cannot be null. (Parameter 'IniFilePath')

### ISSUE THREAD

**Issue by delormej** [delormej/trucks.v2#5]
The following exception occurs when attempting to load fuel csv and the binary is published with --self-contained true -p:PublishSingleFile=true.  This is due to an issue with the underlying Chinchoo CSV library (https://github.com/Cinchoo/ChoETL/blob/997b4ed827f27daac26f5a4df6760d4c714eec61/src/ChoETL/Common/ChoIniFile.cs).

Work around for now is to NOT compile to single file.

1) Exception Information
*********************************************
Exception Type: System.ArgumentNullException
Message: Value cannot be null. (Parameter 'IniFilePath')
ParamName: IniFilePath
TargetSite: Void ArgumentNotNullOrEmpty(System.String, System.String)
Data: System.Collections.ListDictionaryInternal
HelpLink: NULL
Source: ChoETL.Core
HResult: -2147467261

StackTrace Information
*********************************************
   at ChoETL.ChoGuard.ArgumentNotNullOrEmpty(String argumentValue, String argumentName)
   at ChoETL.ChoIniFile.New(String iniFilePath, String sectionName)
   at ChoETL.ChoETLFramework._Initialize()

// Tried the following workarounds, but IsSandboxEnvironment = true throws new errors and doesn't parse the CSV file.

        public async Task SaveFuelAsync(Stream fuelCsvStream)
        {
            // ChoETLFrxBootstrap.IsSandboxEnvironment = true;
            // ChoETLFrxBootstrap.EnableLoadingReferencedAssemblies = false;

**Comment by delormej** [comment]
Upgraded to the .NET (Core) version of the library and resolved.
